# Generated by Django 5.2.6 on 2025-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='slug',
            field=models.SlugField(default='x', max_length=100),
            preserve_default=False,
        ),
    ]
