# Generated by Django 5.2.6 on 2025-12-18 13:02

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_council_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='council',
            name='address',
            field=models.TextField(default='Address not specified'),
        ),
        migrations.AddField(
            model_name='council',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='council_logos/'),
        ),
        migrations.AddField(
            model_name='council',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='blueprint',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 17)),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Location not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='council',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply_chain.council'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='New Project', max_length=200),
        ),
        migrations.CreateModel(
            name='ContractorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='Project Team', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='supply_chain.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('council', 'Council'), ('contractor', 'Contractor')], default='contractor', max_length=20)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Work Package', max_length=200)),
                ('description', models.TextField(default='Work package description')),
                ('category', models.CharField(choices=[('excavation', 'Excavation'), ('traffic', 'Traffic Control'), ('surfacing', 'Road Surfacing'), ('painting', 'Line Painting'), ('facilities', 'Facilities & Sanitation'), ('catering', 'Catering'), ('waste', 'Waste Disposal'), ('equipment', 'Equipment Hire'), ('management', 'Management Services'), ('other', 'Other')], default='other', max_length=50)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField(default=datetime.date(2026, 1, 1))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='supply_chain.project')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Document', max_length=200)),
                ('document_type', models.CharField(choices=[('blueprint', 'Blueprint'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='supply_chain.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='supply_chain.workpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposed_timeline', models.IntegerField(default=7, help_text='Timeline in days')),
                ('experience_summary', models.TextField(default='Experience summary')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='bid_certifications/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='bid_insurance/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_submitted', to=settings.AUTH_USER_MODEL)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='supply_chain.workpackage')),
            ],
            options={
                'ordering': ['amount'],
                'unique_together': {('work_package', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.bid')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='supply_chain.contractorteam')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.workpackage')),
            ],
            options={
                'unique_together': {('team', 'work_package')},
            },
        ),
    ]
