# Generated by Django 5.2.6 on 2025-12-19 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_council_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 18)),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='category',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('concrete', 'Concrete'), ('finishing', 'Finishing'), ('furnishing', 'Furnishing'), ('technician', 'Technician'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 1, 2)),
        ),
    ]
