# Generated by Django 5.2.6 on 2025-12-21 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_alter_project_end_date_alter_workpackage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 20)),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 1, 4)),
        ),
    ]
