# Generated by Django 6.0 on 2025-12-22 04:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_alter_project_end_date_alter_workpackage_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='council',
        ),
        migrations.AddField(
            model_name='project',
            name='council_user',
            field=models.ForeignKey(limit_choices_to={'userprofile__user_type': 'council'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 21)),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 1, 5)),
        ),
    ]
