# Generated by Django 5.2.6 on 2025-12-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_remove_project_council_project_council_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorteam',
            options={'verbose_name': 'Project Team', 'verbose_name_plural': 'Project Teams'},
        ),
    ]
