# Generated by Django 5.2.6 on 2026-01-09 04:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_alter_contractorteam_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 2, 8)),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 1, 23)),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bids_received', models.IntegerField(default=0)),
                ('total_bids_accepted', models.IntegerField(default=0)),
                ('average_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_acceptance_rate', models.FloatField(default=0)),
                ('top_performing_contractor', models.CharField(blank=True, max_length=200)),
                ('days_until_deadline', models.IntegerField(default=0)),
                ('is_on_schedule', models.BooleanField(default=True)),
                ('total_work_packages', models.IntegerField(default=0)),
                ('completed_packages', models.IntegerField(default=0)),
                ('in_progress_packages', models.IntegerField(default=0)),
                ('pending_packages', models.IntegerField(default=0)),
                ('report_data', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='supply_chain.project')),
            ],
            options={
                'verbose_name': 'Project Report',
                'verbose_name_plural': 'Project Reports',
            },
        ),
    ]
